apiVersion: v1
kind: ConfigMap
metadata:
  name: job-portal-config
  namespace: job-portal
data:
  NODE_ENV: production
  PORT: "4000"
  CORS_ORIGIN: "http://job-portal.local"
  AUTH_SERVICE_URL: "http://auth-service:4001"
  USER_SERVICE_URL: "http://user-service:4003"
  JOB_SERVICE_URL: "http://job-service:4002"
  APPLICATION_SERVICE_URL: "http://application-service:4004"
